### ISSUE TITLE
empty local vars causes error

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#403]
sending message server received from client to worker GET-VARS id b'\x00k\x8bEt'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./iiab-cmdsrv3.py", line 697, in cmd_proc_thread
    cmd_resp = cmd_handler(cmd_msg)
  File "./iiab-cmdsrv3.py", line 816, in cmd_handler
    resp = avail_cmds[cmd]["funct"](cmd_info)
  File "./iiab-cmdsrv3.py", line 1046, in get_install_vars
    read_iiab_local_vars() # any errors are raised and caught above
  File "./iiab-cmdsrv3.py", line 3244, in read_iiab_local_vars
    local_vars = adm.jinja2_subst(vars_dict, dflt_dict=default_vars)
  File "/usr/lib/python3/dist-packages/iiab/adm_lib.py", line 962, in jinja2_subst
    lookup_dict = {**dflt_dict,**src_dict}
TypeError: 'NoneType' object is not a mapping

**Comment by tim-moody** [comment]
fixed by #404
