### ISSUE TITLE
oer2go catalog again

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#424]
Traceback (most recent call last):
  File "/opt/admin/cmdsrv/scripts/get_oer2go_catalog", line 183, in <module>
    main()
  File "/opt/admin/cmdsrv/scripts/get_oer2go_catalog", line 103, in main
    for item in oer2go_catalog: # structure of local and remote catalogs is different
TypeError: 'NoneType' object is not iterable
Getting the OER2Go/RACHEL Catalog Failed.

**Comment by tim-moody** [comment]
#425 and #426 fixes
